import {
  Customer,
  Opportunity,
  TimelineEvent,
  AllocationItem,
  VirtualYardStock,
  SalesLogEntry,
  DeliveryHandoverWatch,
  Appointment,
  ConsultantScore,
  AuditLogEntry,
  UserProfile,
} from './types';

export const ASSET_PATHS = {
  officialBrand: '/images/official-byd-melbourne-cbd-lockup.webp',
  officialBrandPng: '/images/official-byd-melbourne-cbd-lockup.png',
  hero: '/images/byd-showroom-hero.webp',
  delivery: '/images/byd-delivery-bay.jpg',
  consultant: '/images/byd-consultant-showroom.jpg',
  testDrive: '/images/byd-test-drive-ready.jpg',
};

export const CURRENT_USER: UserProfile = {
  id: 'usr-001',
  name: 'Alex Rivers',
  email: 'alex.rivers@harmonyauto.com.au',
  role: 'consultant',
  site: 'Fairfield',
  team: 'Fairfield Metro Sales',
  avatarInitials: 'AR',
};

export const ALL_USERS: UserProfile[] = [
  CURRENT_USER,
  {
    id: 'usr-002',
    name: 'Marcus Vance',
    email: 'marcus.vance@harmonyauto.com.au',
    role: 'manager',
    site: 'Fairfield',
    team: 'Fairfield Management',
    avatarInitials: 'MV',
  },
  {
    id: 'usr-003',
    name: 'Elena Rostova',
    email: 'elena.rostova@harmonyauto.com.au',
    role: 'consultant',
    site: 'Melbourne City',
    team: 'Melbourne CBD Flagship',
    avatarInitials: 'ER',
  },
  {
    id: 'usr-004',
    name: 'Chloe Davis',
    email: 'chloe.davis@harmonyauto.com.au',
    role: 'bdc',
    site: 'All Sites',
    team: 'Network BDC',
    avatarInitials: 'CD',
  },
  {
    id: 'usr-005',
    name: 'Rachel Adams',
    email: 'rachel.adams@harmonyauto.com.au',
    role: 'delivery',
    site: 'Fairfield',
    team: 'Handover Operations',
    avatarInitials: 'RA',
  },
  {
    id: 'usr-006',
    name: 'Shaun Sumaru',
    email: 'shaun@omnisuiteai.com',
    role: 'super_admin',
    site: 'All Sites',
    team: 'Harmony Executive',
    avatarInitials: 'SS',
  },
  {
    id: 'usr-007',
    name: 'Harrison Reed',
    email: 'harrison.reed@harmonyauto.com.au',
    role: 'consultant',
    site: 'Fairfield',
    team: 'Fairfield Metro Sales',
    avatarInitials: 'HR',
  },
  {
    id: 'usr-008',
    name: 'Sophia Patel',
    email: 'sophia.patel@harmonyauto.com.au',
    role: 'consultant',
    site: 'Doncaster',
    team: 'Doncaster Sales',
    avatarInitials: 'SP',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    customer_id: 'CUST-0891',
    name: 'Sarah Mitchell',
    phone: '+61412890234',
    email: 'sarah.m@mitchellgroup.com.au',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    source: 'Carsales',
    record_type: 'Individual',
    lead_prospect_id: 'LP-40192',
    consent_sms: true,
    consent_updated_at: '2026-09-20T10:14:00Z',
    do_not_contact: false,
    notes: 'Needs family EV SUV with 500km+ range. Testing SEALION 7 Premium.',
    created_at: '2026-09-18T08:30:00Z',
    total_open_value: 64990,
    current_stage: 'Negotiation',
    active_deal_id: 'OPP-1001',
    active_vy_stock: 'VY-VIC-84920',
  },
  {
    customer_id: 'CUST-0892',
    name: 'Daniel Cho',
    phone: '+61433129881',
    email: 'daniel.cho@choconsulting.com',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    source: 'Virtual Yard',
    record_type: 'Individual',
    lead_prospect_id: 'LP-39912',
    consent_sms: true,
    consent_updated_at: '2026-09-21T14:22:00Z',
    do_not_contact: false,
    notes: 'Novated lease quote requested through Maxxia. Wants SEAL AWD in Cosmos Black.',
    created_at: '2026-09-19T11:00:00Z',
    total_open_value: 68798,
    current_stage: 'Appointment',
    active_deal_id: 'OPP-1002',
    active_vy_stock: 'VY-VIC-81044',
  },
  {
    customer_id: 'CUST-0893',
    name: 'Priya Nair',
    phone: '+61401552901',
    email: 'priya.nair@aushealth.vic.gov.au',
    site: 'Melbourne City',
    owner_user_id: 'usr-003',
    owner_name: 'Elena Rostova',
    source: 'Walk-in',
    record_type: 'Individual',
    lead_prospect_id: 'LP-38821',
    delivery_client_id: 'DC-8841',
    consent_sms: true,
    consent_updated_at: '2026-09-15T09:00:00Z',
    do_not_contact: false,
    notes: 'Deal closed and confirmed. Vehicle in pre-delivery detailing.',
    created_at: '2026-09-10T14:45:00Z',
    total_open_value: 51200,
    current_stage: 'In Delivery',
    active_deal_id: 'OPP-1003',
    active_vy_stock: 'VY-VIC-79102',
  },
  {
    customer_id: 'CUST-0894',
    name: 'Lachlan Smith',
    phone: '+61421773419',
    email: 'l.smith@smithbuild.com.au',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    source: 'Autogate',
    record_type: 'Company',
    company_name: 'Smith Commercial Construction',
    lead_prospect_id: 'LP-41002',
    consent_sms: true,
    consent_updated_at: '2026-09-23T08:15:00Z',
    do_not_contact: false,
    notes: 'Wants Dual-Cab SHARK 6 PHEV with tow bar and heavy duty tray accessories.',
    created_at: '2026-09-23T07:45:00Z',
    total_open_value: 57900,
    current_stage: 'New / Allocated',
    active_deal_id: 'OPP-1004',
  },
  {
    customer_id: 'CUST-0895',
    name: 'Marcus Zhang',
    phone: '+61418902115',
    email: 'marcus.zhang@nextech.io',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    source: 'Web',
    record_type: 'Individual',
    lead_prospect_id: 'LP-40510',
    consent_sms: true,
    consent_updated_at: '2026-09-22T16:00:00Z',
    do_not_contact: false,
    notes: 'Completed CBD test drive loop. Reviewing trade-in quote on 2021 Tesla Model 3.',
    created_at: '2026-09-21T09:30:00Z',
    total_open_value: 65490,
    current_stage: 'Working',
    active_deal_id: 'OPP-1005',
    active_vy_stock: 'VY-VIC-85112',
  },
  {
    customer_id: 'CUST-0896',
    name: 'Apex Logistics Pty Ltd',
    phone: '+61499120334',
    email: 'fleet@apexlogistics.com.au',
    site: 'Melbourne City',
    owner_user_id: 'usr-003',
    owner_name: 'Elena Rostova',
    source: 'Manual',
    record_type: 'Fleet',
    company_name: 'Apex Logistics Fleet VIC',
    delivery_client_id: 'DC-8890',
    consent_sms: true,
    consent_updated_at: '2026-09-12T11:00:00Z',
    do_not_contact: false,
    notes: 'Order confirmed for 3x ATTO 3 Extended pool vehicles.',
    created_at: '2026-09-08T10:00:00Z',
    total_open_value: 148500,
    current_stage: 'Written / Sold',
    active_deal_id: 'OPP-1006',
    active_vy_stock: 'VY-VIC-76011',
  },
  {
    customer_id: 'CUST-0897',
    name: 'Emma Watson',
    phone: '+61403889104',
    email: 'emma.watson@designer.melb',
    site: 'Doncaster',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    source: 'Carsales',
    record_type: 'Individual',
    lead_prospect_id: 'LP-39100',
    consent_sms: false,
    consent_updated_at: '2026-09-18T15:30:00Z',
    do_not_contact: true,
    notes: 'Decided to retain existing vehicle due to job relocation. Marked parked.',
    created_at: '2026-09-14T10:00:00Z',
    total_open_value: 0,
    current_stage: 'Lost / Parked',
    active_deal_id: 'OPP-1007',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    opportunity_id: 'OPP-1001',
    customer_id: 'CUST-0891',
    customer_name: 'Sarah Mitchell',
    customer_phone: '+61412890234',
    customer_email: 'sarah.m@mitchellgroup.com.au',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'Negotiation',
    vehicle_descriptor: 'BYD SEALION 7 Premium AWD',
    model: 'SEALION 7',
    variant: 'Premium AWD',
    colour: 'Atlantis Grey / Black Leather',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-84920',
    vy_order_id: 'VYO-77419',
    sale_type: 'Retail',
    list_price: 65990,
    discount: 1000,
    extras: 0,
    total_deal_value: 64990,
    trade_in_flag: true,
    trade_in_details: {
      makeModel: '2019 Mazda CX-5 Touring',
      rego: '1QX-4KL',
      year: 2019,
      valuation: 22500,
      status: 'Accepted',
    },
    expected_close: '2026-09-26',
    next_action_at: '2026-09-24T10:00:00Z',
    next_action_text: 'Present final changeover figures with tint & mats package',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-18T08:35:00Z',
    updated_at: '2026-09-23T11:20:00Z',
  },
  {
    opportunity_id: 'OPP-1002',
    customer_id: 'CUST-0892',
    customer_name: 'Daniel Cho',
    customer_phone: '+61433129881',
    customer_email: 'daniel.cho@choconsulting.com',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'Appointment',
    vehicle_descriptor: 'BYD SEAL Performance AWD',
    model: 'SEAL',
    variant: 'Performance AWD',
    colour: 'Cosmos Black / Thaumas Black',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-81044',
    sale_type: 'Novated',
    list_price: 68798,
    discount: 0,
    extras: 1200,
    total_deal_value: 69998,
    trade_in_flag: false,
    expected_close: '2026-09-30',
    next_action_at: '2026-09-23T14:30:00Z',
    next_action_text: 'Showroom test drive appointment with salary sacrifice rep',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-19T11:05:00Z',
    updated_at: '2026-09-22T17:15:00Z',
  },
  {
    opportunity_id: 'OPP-1003',
    customer_id: 'CUST-0893',
    customer_name: 'Priya Nair',
    customer_phone: '+61401552901',
    customer_email: 'priya.nair@aushealth.vic.gov.au',
    site: 'Melbourne City',
    owner_user_id: 'usr-003',
    owner_name: 'Elena Rostova',
    stage: 'In Delivery',
    vehicle_descriptor: 'BYD ATTO 3 Extended',
    model: 'ATTO 3',
    variant: 'Extended Range',
    colour: 'Surf Blue / Eclipse Blue',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-79102',
    vy_order_id: 'VYO-76290',
    sales_log_id: 'SL-2026-09-029',
    delivery_client_id: 'DC-8841',
    delivery_stage: 'Pre-Delivery Inspection',
    sale_type: 'Retail',
    list_price: 51200,
    discount: 0,
    extras: 500,
    total_deal_value: 51700,
    trade_in_flag: false,
    expected_close: '2026-09-21',
    next_action_at: '2026-09-25T11:00:00Z',
    next_action_text: 'Handover ceremony in Melbourne City Delivery Bay 1',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-10T14:50:00Z',
    updated_at: '2026-09-23T09:10:00Z',
  },
  {
    opportunity_id: 'OPP-1004',
    customer_id: 'CUST-0894',
    customer_name: 'Lachlan Smith',
    customer_phone: '+61421773419',
    customer_email: 'l.smith@smithbuild.com.au',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'New / Allocated',
    vehicle_descriptor: 'BYD SHARK 6 Dual-Cab PHEV',
    model: 'SHARK 6',
    variant: 'Premium Dual-Cab 4WD',
    colour: 'Trekking Green / Charcoal',
    order_type: 'Factory Order',
    sale_type: 'Fleet',
    list_price: 57900,
    discount: 0,
    extras: 2500,
    total_deal_value: 60400,
    trade_in_flag: true,
    expected_close: '2026-10-05',
    next_action_at: '2026-09-23T09:00:00Z',
    next_action_text: 'SLA Action: Immediate phone outreach for test-drive booking',
    is_overdue: true,
    sync_status: 'synced',
    created_at: '2026-09-23T07:48:00Z',
    updated_at: '2026-09-23T07:48:00Z',
  },
  {
    opportunity_id: 'OPP-1005',
    customer_id: 'CUST-0895',
    customer_name: 'Marcus Zhang',
    customer_phone: '+61418902115',
    customer_email: 'marcus.zhang@nextech.io',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'Working',
    vehicle_descriptor: 'BYD SEALION 7 Performance AWD',
    model: 'SEALION 7',
    variant: 'Performance Dual-Motor',
    colour: 'Aurora White / Black',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-85112',
    sale_type: 'Retail',
    list_price: 69990,
    discount: 500,
    extras: 0,
    total_deal_value: 69490,
    trade_in_flag: true,
    trade_in_details: {
      makeModel: '2021 Tesla Model 3 Standard Range Plus',
      rego: '1VF-8BB',
      year: 2021,
      valuation: 34000,
      status: 'Valued',
    },
    expected_close: '2026-09-28',
    next_action_at: '2026-09-24T16:00:00Z',
    next_action_text: 'Send detailed battery warranty vs Model 3 comparison sheet',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-21T09:35:00Z',
    updated_at: '2026-09-23T14:10:00Z',
  },
  {
    opportunity_id: 'OPP-1006',
    customer_id: 'CUST-0896',
    customer_name: 'Apex Logistics Pty Ltd',
    customer_phone: '+61499120334',
    customer_email: 'fleet@apexlogistics.com.au',
    site: 'Melbourne City',
    owner_user_id: 'usr-003',
    owner_name: 'Elena Rostova',
    stage: 'Written / Sold',
    vehicle_descriptor: 'BYD ATTO 3 Fleet Pack (3 Units)',
    model: 'ATTO 3',
    variant: 'Extended Range Standard Fleet',
    colour: 'Ski White',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-76011',
    vy_order_id: 'VYO-75988',
    sales_log_id: 'SL-2026-09-038',
    delivery_client_id: 'DC-8890',
    delivery_stage: 'Scheduled',
    sale_type: 'Fleet',
    list_price: 153600,
    discount: 5100,
    extras: 0,
    total_deal_value: 148500,
    trade_in_flag: false,
    expected_close: '2026-09-22',
    next_action_at: '2026-09-26T14:00:00Z',
    next_action_text: 'Verify Fleet Novation & EFT payment remittance',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-08T10:10:00Z',
    updated_at: '2026-09-22T17:40:00Z',
  },
  {
    opportunity_id: 'OPP-1007',
    customer_id: 'CUST-0897',
    customer_name: 'Emma Watson',
    customer_phone: '+61403889104',
    customer_email: 'emma.watson@designer.melb',
    site: 'Doncaster',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'Lost / Parked',
    vehicle_descriptor: 'BYD DOLPHIN Premium',
    model: 'DOLPHIN',
    variant: 'Premium Extended',
    colour: 'Coral Pink / Urban Grey',
    order_type: 'Stock',
    sale_type: 'Retail',
    list_price: 44890,
    discount: 0,
    extras: 0,
    total_deal_value: 44890,
    trade_in_flag: false,
    expected_close: '2026-09-18',
    next_action_at: '2026-12-01T09:00:00Z',
    next_action_text: 'Long-term nurture quarterly check-in (Relocated)',
    lost_reason: 'Opted Out',
    lost_notes: 'Relocating to London in Q4. Not proceeding with purchase.',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2026-09-14T10:15:00Z',
    updated_at: '2026-09-18T16:00:00Z',
  },
  {
    opportunity_id: 'OPP-1008',
    customer_id: 'CUST-0891',
    customer_name: 'Sarah Mitchell',
    customer_phone: '+61412890234',
    customer_email: 'sarah.m@mitchellgroup.com.au',
    site: 'Fairfield',
    owner_user_id: 'usr-001',
    owner_name: 'Alex Rivers',
    stage: 'Delivered / Won',
    vehicle_descriptor: 'BYD ATTO 3 Standard (Previous 2024 Deal)',
    model: 'ATTO 3',
    variant: 'Standard Range',
    colour: 'Forest Green',
    order_type: 'Stock',
    vy_stock_id: 'VY-VIC-61002',
    vy_order_id: 'VYO-51200',
    sales_log_id: 'SL-2024-11-018',
    delivery_client_id: 'DC-6019',
    delivery_stage: 'Delivered',
    sale_type: 'Retail',
    list_price: 48990,
    discount: 0,
    extras: 0,
    total_deal_value: 48990,
    trade_in_flag: false,
    expected_close: '2024-11-15',
    next_action_at: '2026-11-15T09:00:00Z',
    next_action_text: '2-Year ownership anniversary & trade-up review',
    is_overdue: false,
    sync_status: 'synced',
    created_at: '2024-11-01T10:00:00Z',
    updated_at: '2024-11-20T14:00:00Z',
  },
];

export const INITIAL_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    event_id: 'EVT-9001',
    customer_id: 'CUST-0891',
    opportunity_id: 'OPP-1001',
    occurred_at: 'Today at 2:15 PM AEST',
    source: 'Sales CRM',
    type: 'note',
    author: 'Alex Rivers (Consultant)',
    title: 'Customer Negotiations Update',
    content: 'Sarah reviewed the trade-in value on the Mazda CX-5 ($22,500). Agreed to proceed if we include ceramic window tint and boot protector mat.',
    visibility: 'internal',
  },
  {
    event_id: 'EVT-9002',
    customer_id: 'CUST-0891',
    opportunity_id: 'OPP-1001',
    occurred_at: 'Today at 1:40 PM AEST',
    source: 'Virtual Yard',
    type: 'vy_stock_event',
    author: 'Virtual Yard Connector',
    title: 'Stock Reserved: VY-VIC-84920',
    content: 'Stock unit SEALION 7 Premium (VIN: 6T1BYD779X2910488) successfully held against Opportunity OPP-1001 for 48 hours.',
    visibility: 'internal',
  },
  {
    event_id: 'EVT-9003',
    customer_id: 'CUST-0891',
    opportunity_id: 'OPP-1001',
    occurred_at: 'Today at 11:20 AM AEST',
    source: 'Lead Centre',
    type: 'sms_in',
    author: 'Sarah Mitchell',
    title: 'Inbound SMS',
    content: '"Hi Alex, loved the test drive this morning! The ride on Punt Rd was super smooth. Can you send through the numbers with the CX-5 trade-in?"',
    visibility: 'customer-facing',
    deep_link: {
      label: 'View SMS in Lead Centre',
      url: 'https://byd-leads-crm.vercel.app/conversations/40192',
    },
  },
  {
    event_id: 'EVT-9004',
    customer_id: 'CUST-0891',
    opportunity_id: 'OPP-1001',
    occurred_at: 'Today at 9:30 AM AEST',
    source: 'Sales CRM',
    type: 'appointment',
    author: 'Alex Rivers',
    title: 'Test Drive Completed',
    content: 'Conducted 45-minute CBD/Freeway evaluation loop in SEALION 7 Demo (VIN ending 9488). Customer was impressed by HUD and NVH levels.',
    visibility: 'internal',
  },
  {
    event_id: 'EVT-9005',
    customer_id: 'CUST-0891',
    occurred_at: 'Yesterday at 4:50 PM AEST',
    source: 'Lead Centre',
    type: 'assignment',
    author: 'Lead Centre AI / BDC',
    title: 'Lead Allocated to Fairfield Sales Desk',
    content: 'Prospect qualified via two-way SMS with intent score 86/100. Allocated to consultant Alex Rivers with 15-minute SLA.',
    visibility: 'internal',
    deep_link: {
      label: 'Open Prospect in Lead Centre',
      url: 'https://byd-leads-crm.vercel.app/leads/40192',
    },
  },
  {
    event_id: 'EVT-9006',
    customer_id: 'CUST-0893',
    opportunity_id: 'OPP-1003',
    occurred_at: 'Today at 9:10 AM AEST',
    source: 'Delivery Centre',
    type: 'delivery_stage_change',
    author: 'Rachel Adams (Delivery Specialist)',
    title: 'Delivery Stage Updated: Pre-Delivery Inspection',
    content: 'Vehicle arrived from Holding Yard VIC. Pre-delivery safety inspection initiated in Workshop Bay 3. Window tint scheduled for 2:00 PM.',
    visibility: 'internal',
    deep_link: {
      label: 'Open in Delivery Centre',
      url: 'https://deliverycentre.com.au/clients/DC-8841',
    },
  },
  {
    event_id: 'EVT-9007',
    customer_id: 'CUST-0893',
    opportunity_id: 'OPP-1003',
    occurred_at: '21 Sep 2026 at 3:15 PM AEST',
    source: 'Sales Log',
    type: 'sales_log_write',
    author: 'Sales CRM Transaction Engine',
    title: 'Sales Log Row Upserted',
    content: 'Deal written by Elena Rostova logged to official Sales Log as SL-2026-09-029. Retail deal value $51,700 confirmed with accounts.',
    visibility: 'internal',
  },
  {
    event_id: 'EVT-9008',
    customer_id: 'CUST-0894',
    opportunity_id: 'OPP-1004',
    occurred_at: 'Today at 7:48 AM AEST',
    source: 'Lead Centre',
    type: 'assignment',
    author: 'Autogate Inbound Engine',
    title: 'Commercial Fleet Enquiry Received',
    content: 'Lachlan Smith enquired on SHARK 6 Dual-Cab PHEV through Autogate. Immediate callback requested before 10 AM.',
    visibility: 'internal',
  },
];

export const INITIAL_ALLOCATIONS: AllocationItem[] = [
  {
    allocation_id: 'ALC-301',
    customer_id: 'CUST-0894',
    prospect_name: 'Lachlan Smith',
    phone: '+61421773419',
    email: 'l.smith@smithbuild.com.au',
    vehicle: 'SHARK 6 Dual-Cab PHEV',
    source: 'Autogate',
    site: 'Fairfield',
    ai_score: 89,
    last_sms_summary: 'Requested towing capacity info and commercial asset write-off availability',
    allocated_at: '2026-09-23T07:45:00Z',
    sla_minutes: 15,
    sla_deadline: '2026-09-23T08:00:00Z',
    status: 'escalated',
    assigned_to: 'Alex Rivers',
    lead_prospect_id: 'LP-41002',
  },
  {
    allocation_id: 'ALC-302',
    customer_id: 'CUST-0898',
    prospect_name: 'Jessica Tan',
    phone: '+61411559821',
    email: 'jess.tan@biotech.com.au',
    vehicle: 'SEALION 7 Sport',
    source: 'Virtual Yard',
    site: 'Fairfield',
    ai_score: 94,
    last_sms_summary: 'Configured Atlantis Grey with panoramic glass roof. Test drive requested Saturday 11am',
    allocated_at: '2026-09-23T09:12:00Z',
    sla_minutes: 15,
    sla_deadline: '2026-09-23T09:27:00Z',
    status: 'pending',
    assigned_to: 'Alex Rivers',
    appointment_booked: 'Sat 27 Sep 11:00 AM',
    lead_prospect_id: 'LP-41008',
  },
  {
    allocation_id: 'ALC-303',
    customer_id: 'CUST-0899',
    prospect_name: 'David O\'Connor',
    phone: '+61400223918',
    email: 'david.oc@melbcorp.com',
    vehicle: 'SEAL Premium AWD',
    source: 'Carsales',
    site: 'Melbourne City',
    ai_score: 72,
    last_sms_summary: 'Comparing ATTO 3 vs SEAL boot dimensions for pram & golf bags',
    allocated_at: '2026-09-23T08:50:00Z',
    sla_minutes: 15,
    sla_deadline: '2026-09-23T09:05:00Z',
    status: 'accepted',
    assigned_to: 'Elena Rostova',
    lead_prospect_id: 'LP-40989',
  },
];

export const INITIAL_VY_STOCK: VirtualYardStock[] = [
  {
    stock_id: 'VY-VIC-84920',
    vin: '6T1BYD779X2910488',
    model: 'SEALION 7',
    variant: 'Premium AWD',
    colour: 'Atlantis Grey',
    location: 'Fairfield Showroom Yard',
    status: 'Held',
    held_by_consultant: 'Alex Rivers',
    held_for_customer: 'Sarah Mitchell',
    held_opportunity_id: 'OPP-1001',
    hold_expires_at: '2026-09-25T13:40:00Z',
    eta_days: 0,
    retail_price: 65990,
  },
  {
    stock_id: 'VY-VIC-81044',
    vin: '6T1BYD881K1088210',
    model: 'SEAL',
    variant: 'Performance AWD',
    colour: 'Cosmos Black',
    location: 'Fairfield Yard Bay 4',
    status: 'Available',
    eta_days: 0,
    retail_price: 68798,
  },
  {
    stock_id: 'VY-VIC-79102',
    vin: '6T1BYD662J9001429',
    model: 'ATTO 3',
    variant: 'Extended Range',
    colour: 'Surf Blue',
    location: 'Melbourne CBD Showroom',
    status: 'Sold',
    held_for_customer: 'Priya Nair',
    held_opportunity_id: 'OPP-1003',
    eta_days: 0,
    retail_price: 51200,
  },
  {
    stock_id: 'VY-VIC-85112',
    vin: '6T1BYD779X2910502',
    model: 'SEALION 7',
    variant: 'Performance Dual-Motor',
    colour: 'Aurora White',
    location: 'Holding Yard VIC (Altona)',
    status: 'Available',
    eta_days: 2,
    retail_price: 69990,
  },
  {
    stock_id: 'VY-VIC-89020',
    vin: '6T1BYD993Z8102994',
    model: 'SHARK 6',
    variant: 'Premium Dual-Cab 4WD',
    colour: 'Trekking Green',
    location: 'Inbound Vessel (Port of Melbourne)',
    status: 'Inbound',
    eta_days: 6,
    retail_price: 57900,
  },
  {
    stock_id: 'VY-VIC-76011',
    vin: '6T1BYD662J9001188',
    model: 'ATTO 3',
    variant: 'Extended Range Standard Fleet',
    colour: 'Ski White',
    location: 'Holding Yard VIC (Altona)',
    status: 'Sold',
    held_for_customer: 'Apex Logistics Pty Ltd',
    held_opportunity_id: 'OPP-1006',
    eta_days: 1,
    retail_price: 51200,
  },
  {
    stock_id: 'VY-VIC-90214',
    vin: '6T1BYD551W4001928',
    model: 'DOLPHIN',
    variant: 'Premium Extended',
    colour: 'Maldive Purple',
    location: 'Doncaster Showroom',
    status: 'Available',
    eta_days: 0,
    retail_price: 44890,
  },
];

export const INITIAL_SALES_LOG: SalesLogEntry[] = [
  {
    sales_log_id: 'SL-2026-09-041',
    deal_date: '2026-09-22',
    customer_name: 'Apex Logistics Pty Ltd',
    vehicle: 'BYD ATTO 3 Fleet Pack (3 Units)',
    vin: '6T1BYD662J9001188',
    stock_id: 'VY-VIC-76011',
    sale_type: 'Fleet',
    consultant: 'Elena Rostova',
    site: 'Melbourne City',
    amount: 148500,
    gross: 11400,
    reconciled: true,
    crm_opportunity_id: 'OPP-1006',
  },
  {
    sales_log_id: 'SL-2026-09-029',
    deal_date: '2026-09-21',
    customer_name: 'Priya Nair',
    vehicle: 'BYD ATTO 3 Extended',
    vin: '6T1BYD662J9001429',
    stock_id: 'VY-VIC-79102',
    sale_type: 'Retail',
    consultant: 'Elena Rostova',
    site: 'Melbourne City',
    amount: 51700,
    gross: 3950,
    reconciled: true,
    crm_opportunity_id: 'OPP-1003',
  },
  {
    sales_log_id: 'SL-2026-09-024',
    deal_date: '2026-09-19',
    customer_name: 'George Karras',
    vehicle: 'BYD SEAL Premium AWD',
    vin: '6T1BYD881K1087401',
    stock_id: 'VY-VIC-79911',
    sale_type: 'Retail',
    consultant: 'Alex Rivers',
    site: 'Fairfield',
    amount: 67990,
    gross: 4800,
    reconciled: true,
    crm_opportunity_id: 'OPP-0992',
  },
];

export const INITIAL_DELIVERY_WATCH: DeliveryHandoverWatch[] = [
  {
    client_id: 'DC-8841',
    opportunity_id: 'OPP-1003',
    customer_name: 'Priya Nair',
    phone: '+61401552901',
    vehicle: 'BYD ATTO 3 Extended',
    vin: '6T1BYD662J9001429',
    rego: '1ZD-9KP',
    stage: 'Pre-Delivery Inspection',
    delivery_date: '2026-09-25',
    delivery_consultant: 'Rachel Adams',
    handover_specialist: 'Rachel Adams',
    contact_status: 'Booked',
    docs_completeness: 'Complete',
    docs_status: {
      atrSigned: true,
      licenceFront: true,
      insurance: true,
      paymentSettled: true,
    },
    arrived: true,
    last_comment: 'PDI checklist passed with zero defects. Ceramic tint applied. Ready for Friday 11am handover.',
  },
  {
    client_id: 'DC-8890',
    opportunity_id: 'OPP-1006',
    customer_name: 'Apex Logistics Pty Ltd',
    phone: '+61499120334',
    vehicle: 'BYD ATTO 3 Extended (3 Units)',
    vin: '6T1BYD662J9001188',
    rego: 'Awaiting VIN',
    stage: 'Scheduled',
    delivery_date: '2026-09-29',
    delivery_consultant: 'Liam Walker',
    handover_specialist: 'Liam Walker',
    contact_status: 'Contacted',
    docs_completeness: 'Partial',
    docs_status: {
      atrSigned: true,
      licenceFront: true,
      insurance: false,
      paymentSettled: false,
    },
    arrived: false,
    last_comment: 'Inbound carrier scheduled from Altona yard Monday 9am. Awaiting insurance certificates from fleet manager.',
    alert: 'Missing Fleet Insurance Schedule',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    appointment_id: 'APT-501',
    customer_id: 'CUST-0891',
    customer_name: 'Sarah Mitchell',
    phone: '+61412890234',
    type: 'Test Drive',
    when: '2026-09-23T09:30:00Z',
    duration_minutes: 45,
    vehicle: 'SEALION 7 Premium AWD',
    loop: 'Fairfield Yarra Bend & Eastern Freeway Loop',
    consultant: 'Alex Rivers',
    site: 'Fairfield',
    status: 'Completed',
    notes: 'Focus on cabin quietness, adaptive cruise and blind spot camera displays.',
  },
  {
    appointment_id: 'APT-502',
    customer_id: 'CUST-0892',
    customer_name: 'Daniel Cho',
    phone: '+61433129881',
    type: 'Test Drive',
    when: '2026-09-23T14:30:00Z',
    duration_minutes: 45,
    vehicle: 'SEAL Performance AWD',
    loop: 'Heidelberg & Ivanhoe Hill Loop',
    consultant: 'Alex Rivers',
    site: 'Fairfield',
    status: 'Confirmed',
    notes: 'Salary sacrifice comparison on performance variant.',
  },
  {
    appointment_id: 'APT-503',
    customer_id: 'CUST-0898',
    customer_name: 'Jessica Tan',
    phone: '+61411559821',
    type: 'Showroom Visit',
    when: '2026-09-27T11:00:00Z',
    duration_minutes: 30,
    vehicle: 'SEALION 7 Sport',
    consultant: 'Alex Rivers',
    site: 'Fairfield',
    status: 'Confirmed',
    notes: 'Colour selection and baby capsule ISOFIX fitment check.',
  },
];

export const CONSULTANT_SCORES: ConsultantScore[] = [
  {
    name: 'Alex Rivers',
    site: 'Fairfield',
    written_units_mtd: 14,
    target_units: 18,
    written_gross_mtd: 68400,
    open_deals_count: 22,
    overdue_actions_count: 1,
    conversion_rate_pct: 38.2,
    avg_first_touch_minutes: 9.4,
  },
  {
    name: 'Elena Rostova',
    site: 'Melbourne City',
    written_units_mtd: 19,
    target_units: 20,
    written_gross_mtd: 91200,
    open_deals_count: 28,
    overdue_actions_count: 0,
    conversion_rate_pct: 44.5,
    avg_first_touch_minutes: 7.1,
  },
  {
    name: 'Harrison Reed',
    site: 'Fairfield',
    written_units_mtd: 11,
    target_units: 16,
    written_gross_mtd: 52800,
    open_deals_count: 19,
    overdue_actions_count: 3,
    conversion_rate_pct: 31.0,
    avg_first_touch_minutes: 18.2,
  },
  {
    name: 'Sophia Patel',
    site: 'Doncaster',
    written_units_mtd: 15,
    target_units: 16,
    written_gross_mtd: 73500,
    open_deals_count: 24,
    overdue_actions_count: 1,
    conversion_rate_pct: 39.8,
    avg_first_touch_minutes: 11.0,
  },
];

export const BYD_SMS_TEMPLATES = [
  {
    id: 'tmpl-01',
    title: 'Test Drive Confirmation',
    category: 'Appointment',
    body: 'Hi {{name}}, Alex from BYD Fairfield here! Your test drive in the {{vehicle}} is confirmed for {{time}}. We are located at 345 Heidelberg Rd, Fairfield. Looking forward to showing you the Blade Battery & tech in person.',
  },
  {
    id: 'tmpl-02',
    title: 'Post-Drive Followup & Quote',
    category: 'Negotiation',
    body: 'Hi {{name}}, thank you for test driving the {{vehicle}} today! I have attached the official Harmony Auto changeover quote. Let me know if you would like me to lock in the vehicle hold.',
  },
  {
    id: 'tmpl-03',
    title: 'Stock Availability & Hold Alert',
    category: 'Virtual Yard',
    body: 'Hi {{name}}, great news! We have just received factory allocation for your requested {{vehicle}} in {{colour}}. We can place a 48-hour complimentary hold on VIN {{vin}} so you do not miss out.',
  },
  {
    id: 'tmpl-04',
    title: 'Order Confirmation & Next Steps',
    category: 'Post-Sale',
    body: 'Congratulations {{name}}! Your BYD {{vehicle}} order (Order #{{vy_order_id}}) is officially placed with BYD Fairfield. Our Delivery Consultant will contact you shortly to coordinate handover.',
  },
  {
    id: 'tmpl-05',
    title: 'Novated Lease Package Information',
    category: 'Finance',
    body: 'Hi {{name}}, following our chat regarding Novated Leasing on the {{vehicle}}, here is the FBT-exempt EV calculation pack for your payroll provider. Please reply if you have questions.',
  },
  {
    id: 'tmpl-06',
    title: 'Opt-Out & ACMA Compliance Notice',
    category: 'Compliance',
    body: 'BYD Harmony Auto: You have been successfully unsubscribed from SMS updates. If this was in error or you wish to reconnect, please contact us directly on (03) 9488 2000.',
  },
];

export const INITIAL_AUDIT_LOG: AuditLogEntry[] = [
  {
    audit_id: 'AUD-8801',
    actor: 'Alex Rivers',
    action: 'Stock Hold Placed',
    target_type: 'Stock',
    target_id: 'VY-VIC-84920',
    details: 'Placed 48-hour hold on SEALION 7 Premium against Opportunity OPP-1001',
    source: 'Sales CRM',
    timestamp: '2026-09-23T13:40:12Z',
  },
  {
    audit_id: 'AUD-8802',
    actor: 'Lead Centre Webhook',
    action: 'Lead Intake & SLA Created',
    target_type: 'Customer',
    target_id: 'CUST-0894',
    details: 'Autogate prospect Lachlan Smith received. 15-minute SLA timer started.',
    source: 'Lead Centre',
    timestamp: '2026-09-23T07:45:00Z',
  },
  {
    audit_id: 'AUD-8803',
    actor: 'Elena Rostova',
    action: 'Mark Sold (3-Way Orchestration)',
    target_type: 'Opportunity',
    target_id: 'OPP-1006',
    details: 'Sold marked: VY Order VYO-75988 confirmed, Sales Log SL-2026-09-038 created, Delivery Client DC-8890 created.',
    source: 'Sales CRM',
    timestamp: '2026-09-22T17:40:00Z',
  },
  {
    audit_id: 'AUD-8804',
    actor: 'Rachel Adams',
    action: 'Handover Stage Transition',
    target_type: 'Delivery',
    target_id: 'DC-8841',
    details: 'Moved from Scheduled to Pre-Delivery Inspection. Workshop safety check signed off.',
    source: 'Delivery Centre',
    timestamp: '2026-09-23T09:10:00Z',
  },
];

